name: 🚀 Deploy Production API to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to Production EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@api.threestyle.in << 'EOF'
            cd ~/three-style-api
            git pull origin main
            npm install
            npm run build
            pm2 restart all
          EOF
